use crate::{command::Command, native_menu::NativeMenuCommand};

pub(super) enum AppCommand {
    NewScratch,
    CloseScratch,
    RenameTab,
    ImportFile,
    ExportFile,
    Preferences,
    Quit,
    Undo,
    Redo,
    Cut,
    Copy,
    Paste,
    SelectAll,
    ToggleComments,
    UpperCase,
    LowerCase,
    TitleCase,
    ExpandWord,
    ContractWord,
    ExpandLine,
    ContractLine,
    ExpandBracketPair,
    ContractBracketPair,
    ExpandIndentBlock,
    ContractIndentBlock,
    Indent,
    Outdent,
    DuplicateLines,
    DeleteLines,
    MoveLinesUp,
    MoveLinesDown,
    JoinLines,
    SortLines,
    ReverseLines,
    TrimTrailingWhitespace,
    AddNextMatch,
    AddAllMatches,
    SplitSelectionIntoLines,
    ClearSecondaryCursors,
    Find,
    FindReplace,
    FindUnderCursor,
    SearchInTabs,
    CommandPalette,
    ToggleWrapMode,
    ToggleVisibleWhitespace,
    ToggleIndentGuides,
    ToggleMinimap,
    ToggleStatusBar,
    ToggleTheme,
    GoToLine,
    ToggleBookmark,
    JumpToNextBookmark,
    ClearBookmarks,
    SplitPaneHorizontal,
    SplitPaneVertical,
    ClosePane,
    PinTab,
    MoveTabLeft,
    MoveTabRight,
    ReopenLastClosed,
}

impl From<NativeMenuCommand> for AppCommand {
    fn from(command: NativeMenuCommand) -> Self {
        match command {
            NativeMenuCommand::NewScratch => Self::NewScratch,
            NativeMenuCommand::CloseScratch => Self::CloseScratch,
            NativeMenuCommand::RenameTab => Self::RenameTab,
            NativeMenuCommand::ImportFile => Self::ImportFile,
            NativeMenuCommand::ExportFile => Self::ExportFile,
            NativeMenuCommand::Preferences => Self::Preferences,
            NativeMenuCommand::Quit => Self::Quit,
            NativeMenuCommand::Undo => Self::Undo,
            NativeMenuCommand::Redo => Self::Redo,
            NativeMenuCommand::Cut => Self::Cut,
            NativeMenuCommand::Copy => Self::Copy,
            NativeMenuCommand::Paste => Self::Paste,
            NativeMenuCommand::SelectAll => Self::SelectAll,
            NativeMenuCommand::ToggleComments => Self::ToggleComments,
            NativeMenuCommand::UpperCase => Self::UpperCase,
            NativeMenuCommand::LowerCase => Self::LowerCase,
            NativeMenuCommand::TitleCase => Self::TitleCase,
            NativeMenuCommand::ExpandWord => Self::ExpandWord,
            NativeMenuCommand::ContractWord => Self::ContractWord,
            NativeMenuCommand::ExpandLine => Self::ExpandLine,
            NativeMenuCommand::ContractLine => Self::ContractLine,
            NativeMenuCommand::ExpandBracketPair => Self::ExpandBracketPair,
            NativeMenuCommand::ContractBracketPair => Self::ContractBracketPair,
            NativeMenuCommand::ExpandIndentBlock => Self::ExpandIndentBlock,
            NativeMenuCommand::ContractIndentBlock => Self::ContractIndentBlock,
            NativeMenuCommand::Indent => Self::Indent,
            NativeMenuCommand::Outdent => Self::Outdent,
            NativeMenuCommand::DuplicateLines => Self::DuplicateLines,
            NativeMenuCommand::DeleteLines => Self::DeleteLines,
            NativeMenuCommand::MoveLinesUp => Self::MoveLinesUp,
            NativeMenuCommand::MoveLinesDown => Self::MoveLinesDown,
            NativeMenuCommand::JoinLines => Self::JoinLines,
            NativeMenuCommand::SortLines => Self::SortLines,
            NativeMenuCommand::ReverseLines => Self::ReverseLines,
            NativeMenuCommand::TrimTrailingWhitespace => Self::TrimTrailingWhitespace,
            NativeMenuCommand::AddNextMatch => Self::AddNextMatch,
            NativeMenuCommand::AddAllMatches => Self::AddAllMatches,
            NativeMenuCommand::SplitSelectionIntoLines => Self::SplitSelectionIntoLines,
            NativeMenuCommand::ClearSecondaryCursors => Self::ClearSecondaryCursors,
            NativeMenuCommand::Find => Self::Find,
            NativeMenuCommand::FindReplace => Self::FindReplace,
            NativeMenuCommand::FindUnderCursor => Self::FindUnderCursor,
            NativeMenuCommand::SearchInTabs => Self::SearchInTabs,
            NativeMenuCommand::CommandPalette => Self::CommandPalette,
            NativeMenuCommand::ToggleWrapMode => Self::ToggleWrapMode,
            NativeMenuCommand::ToggleVisibleWhitespace => Self::ToggleVisibleWhitespace,
            NativeMenuCommand::ToggleIndentGuides => Self::ToggleIndentGuides,
            NativeMenuCommand::ToggleMinimap => Self::ToggleMinimap,
            NativeMenuCommand::ToggleStatusBar => Self::ToggleStatusBar,
            NativeMenuCommand::ToggleTheme => Self::ToggleTheme,
            NativeMenuCommand::GoToLine => Self::GoToLine,
            NativeMenuCommand::ToggleBookmark => Self::ToggleBookmark,
            NativeMenuCommand::JumpToNextBookmark => Self::JumpToNextBookmark,
            NativeMenuCommand::ClearBookmarks => Self::ClearBookmarks,
            NativeMenuCommand::SplitPaneHorizontal => Self::SplitPaneHorizontal,
            NativeMenuCommand::SplitPaneVertical => Self::SplitPaneVertical,
            NativeMenuCommand::ClosePane => Self::ClosePane,
            NativeMenuCommand::PinTab => Self::PinTab,
            NativeMenuCommand::MoveTabLeft => Self::MoveTabLeft,
            NativeMenuCommand::MoveTabRight => Self::MoveTabRight,
        }
    }
}

impl AppCommand {
    pub(super) fn from_command(command: Command) -> Option<Self> {
        let app_command = match command {
            Command::NewScratch => Self::NewScratch,
            Command::CloseScratch => Self::CloseScratch,
            Command::RenameTab => Self::RenameTab,
            Command::Cut => Self::Cut,
            Command::Copy => Self::Copy,
            Command::Paste => Self::Paste,
            Command::SelectAll => Self::SelectAll,
            Command::Undo => Self::Undo,
            Command::Redo => Self::Redo,
            Command::Indent => Self::Indent,
            Command::Outdent => Self::Outdent,
            Command::DuplicateLines => Self::DuplicateLines,
            Command::DeleteLines => Self::DeleteLines,
            Command::MoveLinesUp => Self::MoveLinesUp,
            Command::MoveLinesDown => Self::MoveLinesDown,
            Command::JoinLines => Self::JoinLines,
            Command::SortLines => Self::SortLines,
            Command::ReverseLines => Self::ReverseLines,
            Command::TrimTrailingWhitespace => Self::TrimTrailingWhitespace,
            Command::AddNextMatch => Self::AddNextMatch,
            Command::AddAllMatches => Self::AddAllMatches,
            Command::SplitSelectionIntoLines => Self::SplitSelectionIntoLines,
            Command::ClearSecondaryCursors => Self::ClearSecondaryCursors,
            Command::ToggleComments => Self::ToggleComments,
            Command::UpperCase => Self::UpperCase,
            Command::LowerCase => Self::LowerCase,
            Command::TitleCase => Self::TitleCase,
            Command::GoToLine => Self::GoToLine,
            Command::ImportFile => Self::ImportFile,
            Command::ExportFile => Self::ExportFile,
            Command::Preferences => Self::Preferences,
            Command::ToggleBookmark => Self::ToggleBookmark,
            Command::JumpToNextBookmark => Self::JumpToNextBookmark,
            Command::ClearBookmarks => Self::ClearBookmarks,
            Command::SplitPaneHorizontal => Self::SplitPaneHorizontal,
            Command::SplitPaneVertical => Self::SplitPaneVertical,
            Command::ClosePane => Self::ClosePane,
            Command::PinTab => Self::PinTab,
            Command::MoveTabLeft => Self::MoveTabLeft,
            Command::MoveTabRight => Self::MoveTabRight,
            Command::ReopenLastClosed => Self::ReopenLastClosed,
            _ => return None,
        };
        Some(app_command)
    }
}
